exclude: 'node_modules'
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'd821bc8' # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        types: [javascript]
